library(shiny)
library(shinydashboard)
library(dashboardthemes)
library(tidyverse)
library(htmlwidgets)
library(shinyWidgets)
library(rlang)
library(echarts4r)
library(reactable)
library(leaflet)
library(tsibble)
library(lubridate)
library(colorspace)
library(janitor)

invisible(map(paste0("shiny/module/", list.files("shiny/module/")), source))
source("shiny/function.R")
source("shiny/data.R")
source("shiny/ini.R")
source("shiny/ui.R")
source("shiny/server.R")

shinyApp(app_ui, app_server)
